
docker_build:
	docker build -t datasci .

docker_build_tag:
	docker build -t benislocated/data-science-jupyter:latest .

docker_login:
	docker login

docker_push:
	docker push benislocated/data-science-jupyter:latest 
